2023-08-24 19:32:09,810 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-08-25 15:37:59,281 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-04 13:59:59,870 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-04 13:59:59,878 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-04 14:00:50,196 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-04 14:00:50,203 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-04 14:01:04,432 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-04 14:01:04,439 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-04 14:08:04,009 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-04 14:08:04,017 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-04 14:08:18,276 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-04 14:08:18,284 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-04 14:33:51,073 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-04 14:33:51,092 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-04 14:33:58,457 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-04 14:33:58,459 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'get_checkpoint' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 77, in get_checkpoint
    task.host.open_connection("napalm", None)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/inventory.py", line 533, in open_connection
    raise ConnectionAlreadyOpen(conn_name)
nornir.core.exceptions.ConnectionAlreadyOpen: napalm

2023-09-04 14:33:58,459 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'get_checkpoint' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 77, in get_checkpoint
    task.host.open_connection("napalm", None)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/inventory.py", line 533, in open_connection
    raise ConnectionAlreadyOpen(conn_name)
nornir.core.exceptions.ConnectionAlreadyOpen: napalm

2023-09-04 14:34:27,726 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-04 14:34:27,733 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-04 14:34:35,351 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-04 14:38:29,521 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-04 14:38:31,447 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-04 14:38:31,447 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=task.host["intf_config"])
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-04 14:38:31,549 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-04 14:38:31,549 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=task.host["intf_config"])
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-04 14:38:31,550 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-04 14:38:31,550 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-04 14:39:18,034 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-04 14:39:20,134 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-04 14:39:20,135 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-04 14:39:20,624 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-04 14:39:20,625 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-04 14:39:20,625 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-04 14:39:20,626 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-04 14:45:58,080 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-04 14:46:33,448 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 197, in _commit_merge
    output = self._send_config(self.merge_candidate)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 839, in _send_config
    return self.device.config_list(commands)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/device.py", line 135, in config_list
    return self.api._nxapi_command_conf(commands)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 145, in _nxapi_command_conf
    return self._nxapi_command(commands=commands, method=method)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 137, in _nxapi_command
    api_response = self._process_api_response(response, commands, raw_text=raw_text)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 190, in _process_api_response
    self._error_check(response)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 215, in _error_check
    raise NXAPICommandError(command, error["data"]["msg"])
napalm.nxapi_plumbing.errors.NXAPICommandError: The command "task.host["intf_config"]" gave the error "% Invalid command
".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 48, in napalm_configure
    device.commit_config(**commit_kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 290, in commit_config
    self._commit_merge()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 205, in _commit_merge
    raise MergeConfigException(merge_error)
napalm.base.exceptions.MergeConfigException: Configuration merge failed; automatic rollback attempted:
'The command "task.host["intf_config"]" gave the error "% Invalid command\n".'

2023-09-04 14:46:33,449 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=f'task.host["intf_config"]')
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-04 14:46:37,109 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 197, in _commit_merge
    output = self._send_config(self.merge_candidate)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 839, in _send_config
    return self.device.config_list(commands)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/device.py", line 135, in config_list
    return self.api._nxapi_command_conf(commands)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 145, in _nxapi_command_conf
    return self._nxapi_command(commands=commands, method=method)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 137, in _nxapi_command
    api_response = self._process_api_response(response, commands, raw_text=raw_text)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 190, in _process_api_response
    self._error_check(response)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 215, in _error_check
    raise NXAPICommandError(command, error["data"]["msg"])
napalm.nxapi_plumbing.errors.NXAPICommandError: The command "task.host["intf_config"]" gave the error "% Invalid command
".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 48, in napalm_configure
    device.commit_config(**commit_kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 290, in commit_config
    self._commit_merge()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 205, in _commit_merge
    raise MergeConfigException(merge_error)
napalm.base.exceptions.MergeConfigException: Configuration merge failed; automatic rollback attempted:
'The command "task.host["intf_config"]" gave the error "% Invalid command\n".'

2023-09-04 14:46:37,109 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=f'task.host["intf_config"]')
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-04 14:46:37,110 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-04 14:46:37,110 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-09 16:36:58,645 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-09 16:37:34,737 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 197, in _commit_merge
    output = self._send_config(self.merge_candidate)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 839, in _send_config
    return self.device.config_list(commands)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/device.py", line 135, in config_list
    return self.api._nxapi_command_conf(commands)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 145, in _nxapi_command_conf
    return self._nxapi_command(commands=commands, method=method)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 137, in _nxapi_command
    api_response = self._process_api_response(response, commands, raw_text=raw_text)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 190, in _process_api_response
    self._error_check(response)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 215, in _error_check
    raise NXAPICommandError(command, error["data"]["msg"])
napalm.nxapi_plumbing.errors.NXAPICommandError: The command "task.host["intf_config"]" gave the error "% Invalid command
".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 48, in napalm_configure
    device.commit_config(**commit_kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 290, in commit_config
    self._commit_merge()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 205, in _commit_merge
    raise MergeConfigException(merge_error)
napalm.base.exceptions.MergeConfigException: Configuration merge failed; automatic rollback attempted:
'The command "task.host["intf_config"]" gave the error "% Invalid command\n".'

2023-09-09 16:37:34,738 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=f'task.host["intf_config"]')
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-09 16:37:34,893 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 197, in _commit_merge
    output = self._send_config(self.merge_candidate)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 839, in _send_config
    return self.device.config_list(commands)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/device.py", line 135, in config_list
    return self.api._nxapi_command_conf(commands)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 145, in _nxapi_command_conf
    return self._nxapi_command(commands=commands, method=method)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 137, in _nxapi_command
    api_response = self._process_api_response(response, commands, raw_text=raw_text)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 190, in _process_api_response
    self._error_check(response)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 215, in _error_check
    raise NXAPICommandError(command, error["data"]["msg"])
napalm.nxapi_plumbing.errors.NXAPICommandError: The command "task.host["intf_config"]" gave the error "% Invalid command
".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 48, in napalm_configure
    device.commit_config(**commit_kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 290, in commit_config
    self._commit_merge()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 205, in _commit_merge
    raise MergeConfigException(merge_error)
napalm.base.exceptions.MergeConfigException: Configuration merge failed; automatic rollback attempted:
'The command "task.host["intf_config"]" gave the error "% Invalid command\n".'

2023-09-09 16:37:34,894 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=f'task.host["intf_config"]')
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-09 16:37:34,894 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-09 16:37:34,894 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-09 16:45:23,379 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-09 16:45:25,522 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-09 16:45:25,522 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-09 16:45:26,275 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-09 16:45:26,276 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-09 16:45:26,276 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-09 16:45:26,276 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-09 16:47:09,980 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-09 16:47:12,081 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-09 16:47:12,082 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 43, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=host_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-09 16:47:12,173 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-09 16:47:12,174 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 43, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=host_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-09 16:47:12,174 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-09 16:47:12,174 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-09 16:49:02,225 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-09 16:59:00,993 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-09 16:59:53,440 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 197, in _commit_merge
    output = self._send_config(self.merge_candidate)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 839, in _send_config
    return self.device.config_list(commands)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/device.py", line 135, in config_list
    return self.api._nxapi_command_conf(commands)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 145, in _nxapi_command_conf
    return self._nxapi_command(commands=commands, method=method)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 137, in _nxapi_command
    api_response = self._process_api_response(response, commands, raw_text=raw_text)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 190, in _process_api_response
    self._error_check(response)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxapi_plumbing/api_client.py", line 215, in _error_check
    raise NXAPICommandError(command, error["data"]["msg"])
napalm.nxapi_plumbing.errors.NXAPICommandError: The command "task.host["intf_config"]" gave the error "% Invalid command
".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 48, in napalm_configure
    device.commit_config(**commit_kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 290, in commit_config
    self._commit_merge()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 205, in _commit_merge
    raise MergeConfigException(merge_error)
napalm.base.exceptions.MergeConfigException: Configuration merge failed; automatic rollback attempted:
'The command "task.host["intf_config"]" gave the error "% Invalid command\n".'

2023-09-09 17:03:29,863 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-09 17:04:17,913 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-09 17:04:38,597 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-09 17:04:41,135 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-09 17:04:41,136 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-09 17:04:41,138 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-09 17:04:41,139 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-09 17:49:15,870 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-09 17:49:46,796 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-09 17:49:48,947 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-09 17:49:48,948 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-09 17:49:50,001 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-09 17:49:50,002 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 42, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-09 17:49:50,003 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-09 17:49:50,004 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-09 17:50:03,410 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-09 17:50:17,100 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-15 08:29:10,380 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-15 09:18:11,261 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-15 09:43:02,003 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-15 09:43:04,191 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-15 09:43:04,192 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 44, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-15 09:43:05,429 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-15 09:43:05,429 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 44, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-15 09:43:05,430 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-15 09:43:05,430 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-15 09:47:18,010 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-15 09:48:28,791 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 37, in napalm_configure
    diff = device.compare_config()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 269, in compare_config
    return self._get_merge_diff()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 237, in _get_merge_diff
    return diff_network_config(self.merge_candidate, running_config, "cisco_nxos")
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/compliance.py", line 274, in diff_network_config
    compare_parser = os_parser(compare_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 676, in __init__
    super(NXOSConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 524, in __init__
    super(CiscoConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 66, in __init__
    super(BaseSpaceConfigParser, self).__init__(config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 33, in __init__
    self.build_config_relationship()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/netutils/config/parser.py", line 314, in build_config_relationship
    previous_config = self.config_lines[-1]
IndexError: list index out of range

2023-09-15 09:48:40,560 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/ktb.py", line 45, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/usr/local/lib/python3.9/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/usr/local/lib/python3.9/bdb.py", line 174, in dispatch_exception
    if self.quitting: raise BdbQuit
bdb.BdbQuit

2023-09-15 09:48:41,741 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/ktb.py", line 38, in config_interfaces
    intf_multi_result = task.run(task=template_file, template="intf.j2", path=".", **task.host)
  File "/home/delbrugge/nornir-class/bonus_2/ktb.py", line 38, in config_interfaces
    intf_multi_result = task.run(task=template_file, template="intf.j2", path=".", **task.host)
  File "/usr/local/lib/python3.9/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/local/lib/python3.9/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

2023-09-15 09:48:41,742 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-15 09:48:41,742 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-15 09:48:45,015 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-15 09:49:29,827 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-15 09:49:42,179 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 36, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 185, in load_merge_candidate
    assert isinstance(config, str)
AssertionError

2023-09-15 09:49:43,477 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 45, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-15 09:49:44,139 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 36, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 185, in load_merge_candidate
    assert isinstance(config, str)
AssertionError

2023-09-15 09:49:44,140 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'config_interfaces' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 45, in config_interfaces
    intf_result = task.run(task=napalm_configure, configuration=intf_rendered_config)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-09-15 09:49:44,143 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-15 09:49:44,143 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-15 09:52:54,572 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-15 09:53:46,298 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-15 09:53:55,715 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-15 09:58:43,151 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-15 09:59:09,552 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-15 09:59:16,007 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-15 11:36:33,768 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-15 11:37:02,606 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-15 11:37:09,659 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-15 11:37:14,164 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-15 11:37:14,166 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    laksdjf
NameError: name 'laksdjf' is not defined

2023-09-15 11:37:14,166 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    laksdjf
NameError: name 'laksdjf' is not defined

2023-09-19 19:39:48,698 -  nornir.core -     INFO -        run() - Running task 'config_interfaces' with args {} on 2 hosts
2023-09-19 19:40:21,294 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-19 19:40:30,805 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-19 19:40:41,928 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-19 19:40:41,945 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 42, in template_file
    t = env.get_template(template)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "bgp.j2", line 16, in template
    route-map {{ neighbor.route_map_in }} in
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

2023-09-19 19:40:41,946 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    bgp_conf_multi_result = task.run(task=template_file, template="bgp.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-19 19:40:41,947 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 42, in template_file
    t = env.get_template(template)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "bgp.j2", line 16, in template
    route-map {{ neighbor.route_map_in }} in
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

2023-09-19 19:40:41,947 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    bgp_conf_multi_result = task.run(task=template_file, template="bgp.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-19 19:43:05,609 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-19 19:43:05,630 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 42, in template_file
    t = env.get_template(template)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "bgp.j2", line 17, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

2023-09-19 19:43:05,631 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    bgp_conf_multi_result = task.run(task=template_file, template="bgp.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-19 19:43:05,636 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 42, in template_file
    t = env.get_template(template)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "bgp.j2", line 17, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

2023-09-19 19:43:05,638 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    bgp_conf_multi_result = task.run(task=template_file, template="bgp.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 08:24:42,482 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 08:24:42,521 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 42, in template_file
    t = env.get_template(template)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "bgp.j2", line 17, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

2023-09-23 08:24:42,522 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    bgp_conf_multi_result = task.run(task=template_file, template="bgp.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 08:24:42,535 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 42, in template_file
    t = env.get_template(template)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "bgp.j2", line 17, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

2023-09-23 08:24:42,540 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    bgp_conf_multi_result = task.run(task=template_file, template="bgp.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 08:28:01,403 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 08:28:01,434 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "bgp.j2", line 13, in top-level template code
    {% if neighbor.route_map_out %}
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'neighbor' is undefined

2023-09-23 08:28:01,445 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    bgp_conf_multi_result = task.run(task=template_file, template="bgp.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 08:28:01,449 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "bgp.j2", line 13, in top-level template code
    {% if neighbor.route_map_out %}
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'neighbor' is undefined

2023-09-23 08:28:01,450 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    bgp_conf_multi_result = task.run(task=template_file, template="bgp.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 08:29:03,847 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 08:29:03,878 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "bgp.j2", line 15, in top-level template code
    {% if neighbor.route_map_in %}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'route_map_in'

2023-09-23 08:29:03,889 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    bgp_conf_multi_result = task.run(task=template_file, template="bgp.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 08:29:03,893 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "bgp.j2", line 15, in top-level template code
    {% if neighbor.route_map_in %}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'route_map_in'

2023-09-23 08:29:03,893 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    bgp_conf_multi_result = task.run(task=template_file, template="bgp.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 08:32:37,680 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 08:32:37,721 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "bgp.j2", line 13, in top-level template code
    route-map {{ neighbor.route_map_in }} in
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'route_map_in'

2023-09-23 08:32:37,722 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    bgp_conf_multi_result = task.run(task=template_file, template="bgp.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 08:37:37,793 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 08:37:37,830 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "prefix-list.j2", line 1, in top-level template code
    {% for entry in bgp.prefix_lists %}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'prefix_lists'

2023-09-23 08:37:37,831 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 82, in render_configs
    prefix_conf_multi_result = task.run(task=template_file, template="prefix-list.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 08:37:37,832 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "route-map.j2", line 2, in top-level template code
    route-map BMGR-{{ entry.name }} seq {{ entry.seq }} {{ entry.action }} {{ entry.network }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'network'

2023-09-23 08:37:37,833 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 84, in render_configs
    rm_conf_multi_result = task.run(task=template_file, template="route-map.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 08:39:57,887 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 08:39:57,918 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "route-map.j2", line 2, in top-level template code
    route-map BMGR-{{ entry.name }} seq {{ entry.seq }} {{ entry.action }} {{ entry.network }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'network'

2023-09-23 08:39:57,925 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 84, in render_configs
    rm_conf_multi_result = task.run(task=template_file, template="route-map.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 08:39:57,933 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "route-map.j2", line 2, in top-level template code
    route-map BMGR-{{ entry.name }} seq {{ entry.seq }} {{ entry.action }} {{ entry.network }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'network'

2023-09-23 08:39:57,934 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 84, in render_configs
    rm_conf_multi_result = task.run(task=template_file, template="route-map.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 15:59:59,156 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 15:59:59,187 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "route-map.j2", line 2, in top-level template code
    route-map BMGR-{{ entry.name }} seq {{ entry.seq }} {{ entry.action }} {{ entry.network }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'network'

2023-09-23 15:59:59,194 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 84, in render_configs
    rm_conf_multi_result = task.run(task=template_file, template="route-map.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 15:59:59,202 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "route-map.j2", line 2, in top-level template code
    route-map BMGR-{{ entry.name }} seq {{ entry.seq }} {{ entry.action }} {{ entry.network }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'network'

2023-09-23 15:59:59,203 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 84, in render_configs
    rm_conf_multi_result = task.run(task=template_file, template="route-map.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 16:00:21,255 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 16:00:21,286 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "route-map.j2", line 2, in top-level template code
    route-map BMGR-{{ entry.name }} seq {{ entry.seq }} {{ entry.action }} {{ entry.network }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'network'

2023-09-23 16:00:21,293 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 84, in render_configs
    rm_conf_multi_result = task.run(task=template_file, template="route-map.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 16:00:21,301 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "route-map.j2", line 2, in top-level template code
    route-map BMGR-{{ entry.name }} seq {{ entry.seq }} {{ entry.action }} {{ entry.network }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'network'

2023-09-23 16:00:21,302 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 84, in render_configs
    rm_conf_multi_result = task.run(task=template_file, template="route-map.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 16:02:49,473 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 16:02:49,502 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "route-map.j2", line 2, in top-level template code
    route-map BMGR-{{ entry.name }} seq {{ entry.seq }} {{ entry.action }} {{ entry.network }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'network'

2023-09-23 16:02:49,509 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 84, in render_configs
    rm_conf_multi_result = task.run(task=template_file, template="route-map.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 16:02:49,517 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "route-map.j2", line 2, in top-level template code
    route-map BMGR-{{ entry.name }} seq {{ entry.seq }} {{ entry.action }} {{ entry.network }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'network'

2023-09-23 16:02:49,517 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 84, in render_configs
    rm_conf_multi_result = task.run(task=template_file, template="route-map.j2", path=".", **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: template_file (failed)


2023-09-23 16:03:09,168 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 16:06:31,956 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 16:43:06,221 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-23 16:43:17,488 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-23 16:43:21,806 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 16:43:48,062 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-23 16:43:55,828 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-23 16:44:01,151 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 16:44:01,216 -  nornir.core -     INFO -        run() - Running task 'merge_configs' with args {} on 2 hosts
2023-09-23 16:44:01,223 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'merge_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/ciscoconfparse/ciscoconfparse.py", line 270, in __init__
    f = open(config, **self.openargs)
OSError: [Errno 36] File name too long: '\n!Command: Checkpoint cmd vdc 1\n!Time: Sat Sep 23 23:43:58 2023\n\nversion 9.2(3) Bios:version  \nhostname nxos1\nclass-map type network-qos c-nq1\n  description Default class on qos-group 1\n  match qos-group 1\nclass-map type network-qos c-nq2\n  description Default class on qos-group 2\n  match qos-group 2\nclass-map type network-qos c-nq3\n  description Default class on qos-group 3\n  match qos-group 3\nclass-map type network-qos c-8q-nq1\n  description Default class on qos-group 1\n  match qos-group 1\nclass-map type network-qos c-8q-nq2\n  description Default class on qos-group 2\n  match qos-group 2\nclass-map type network-qos c-8q-nq3\n  description Default class on qos-group 3\n  match qos-group 3\nclass-map type network-qos c-8q-nq4\n  description Default class on qos-group 4\n  match qos-group 4\nclass-map type network-qos c-8q-nq5\n  description Default class on qos-group 5\n  match qos-group 5\nclass-map type network-qos c-8q-nq6\n  description Default class on qos-group 6\n  match qos-group 6\nclass-map type network-qos c-8q-nq7\n  description Default class on qos-group 7\n  match qos-group 7\nclass-map type network-qos c-nq-default\n  description Default class on qos-group 0\n  match qos-group 0\nclass-map type network-qos c-8q-nq-default\n  description Default class on qos-group 0\n  match qos-group 0\npolicy-map type network-qos default-nq-policy\n  class type network-qos c-nq3\n    mtu 1500\n  class type network-qos c-nq2\n    mtu 1500\n  class type network-qos c-nq1\n    mtu 1500\n  class type network-qos c-nq-default\n    mtu 1500\npolicy-map type network-qos default-8q-nq-policy\n  class type network-qos c-8q-nq7\n    mtu 1500\n  class type network-qos c-8q-nq6\n    mtu 1500\n  class type network-qos c-8q-nq5\n    mtu 1500\n  class type network-qos c-8q-nq4\n    mtu 1500\n  class type network-qos c-8q-nq3\n    mtu 1500\n  class type network-qos c-8q-nq2\n    mtu 1500\n  class type network-qos c-8q-nq1\n    mtu 1500\n  class type network-qos c-8q-nq-default\n    mtu 1500\nvdc nxos1 id 1\n  limit-resource vlan minimum 16 maximum 4094\n  limit-resource vrf minimum 2 maximum 4096\n  limit-resource port-channel minimum 0 maximum 511\n  limit-resource u4route-mem minimum 128 maximum 128\n  limit-resource u6route-mem minimum 96 maximum 96\n  limit-resource m4route-mem minimum 58 maximum 58\n  limit-resource m6route-mem minimum 8 maximum 8\n\n!#feature ssh\n!#ssh key rsa 1024\nfeature nxapi\nfeature scp-server\ncfs eth distribute\nfeature bgp\nfeature interface-vlan\nfeature hsrp\nfeature vpc\nfeature lldp\n\nrole name priv-15\n  description This is a system defined privilege role.\n  rule 1 permit read-write  \nrole name priv-14\n  description This is a system defined privilege role.\n  rule 1 permit read-write  \nrole name priv-13\n  description This is a system defined privilege role.\nrole name priv-12\n  description This is a system defined privilege role.\nrole name priv-11\n  description This is a system defined privilege role.\nrole name priv-10\n  description This is a system defined privilege role.\nrole name priv-9\n  description This is a system defined privilege role.\nrole name priv-8\n  description This is a system defined privilege role.\nrole name priv-7\n  description This is a system defined privilege role.\nrole name priv-6\n  description This is a system defined privilege role.\nrole name priv-5\n  description This is a system defined privilege role.\nrole name priv-4\n  description This is a system defined privilege role.\nrole name priv-3\n  description This is a system defined privilege role.\nrole name priv-2\n  description This is a system defined privilege role.\nrole name priv-1\n  description This is a system defined privilege role.\nrole name priv-0\n  description This is a system defined privilege role.\n  rule 10 permit command traceroute6 *\n  rule 9 permit command traceroute *\n  rule 8 permit command telnet6 *\n  rule 7 permit command telnet *\n  rule 6 permit command ping6 *\n  rule 5 permit command ping *\n  rule 4 permit command ssh6 *\n  rule 3 permit command ssh *\n  rule 2 permit command enable *\n  rule 1 permit read  \nno password strength-check\nusername admin password 5 $5$/.ErG6en$vIpgmSARIqTv9N7btcIi2Ie9gdJvIAPKtecRH/a14YB  role network-admin\nusername pyclass password 5 $5$/SRuQL7G$xw4WMR3jIUzqHAZs7FWuIbqJMIAjV7UU5w8XawKHl.1  role network-admin\nusername pyclass passphrase  lifetime 99999 warntime 14 gracetime 3\nip domain-lookup\nip domain-name lasthop.io\nip name-server 8.8.8.8 8.8.4.4\nip name-server 10.0.2.3 use-vrf management\nno system default switchport\nno logging event trunk-status enable\nvlan dot1Q tag native\n!# qos statistics\n!# class-map type queuing match-any c-out-q3\n  !# match qos-group 3\n!# class-map type queuing match-any c-out-q2\n  !# match qos-group 2\n!# class-map type queuing match-any c-out-q1\n  !# match qos-group 1\n!# class-map type queuing match-any c-out-q-default\n  !# match qos-group 0\n!# class-map type queuing match-any c-out-8q-q7\n  !# match qos-group 7\n!# class-map type queuing match-any c-out-8q-q6\n  !# match qos-group 6\n!# class-map type queuing match-any c-out-8q-q5\n  !# match qos-group 5\n!# class-map type queuing match-any c-out-8q-q4\n  !# match qos-group 4\n!# class-map type queuing match-any c-out-8q-q3\n  !# match qos-group 3\n!# class-map type queuing match-any c-out-8q-q2\n  !# match qos-group 2\n!# class-map type queuing match-any c-out-8q-q1\n  !# match qos-group 1\n!# class-map type queuing match-any c-out-8q-q-default\n  !# match qos-group 0\n!# class-map type queuing match-any c-in-q7\n  !# match qos-group 7\n!# class-map type queuing match-any c-in-q6\n  !# match qos-group 6\n!# class-map type queuing match-any c-in-q5\n  !# match qos-group 5\n!# class-map type queuing match-any c-in-q4\n  !# match qos-group 4\n!# class-map type queuing match-any c-in-q3\n  !# match qos-group 3\n!# class-map type queuing match-any c-in-q2\n  !# match qos-group 2\n!# class-map type queuing match-any c-in-q1\n  !# match qos-group 1\n!# class-map type queuing match-any c-in-q-default\n  !# match qos-group 0\npolicy-map type queuing default-out-policy\n  class type queuing c-out-q3\n    priority level 1\n  class type queuing c-out-q2\n    bandwidth remaining percent 0\n  class type queuing c-out-q1\n    bandwidth remaining percent 0\n  class type queuing c-out-q-default\n    bandwidth remaining percent 100\npolicy-map type queuing default-8q-out-policy\n  class type queuing c-out-8q-q7\n    priority level 1\n  class type queuing c-out-8q-q6\n    bandwidth remaining percent 0\n  class type queuing c-out-8q-q5\n    bandwidth remaining percent 0\n  class type queuing c-out-8q-q4\n    bandwidth remaining percent 0\n  class type queuing c-out-8q-q3\n    bandwidth remaining percent 0\n  class type queuing c-out-8q-q2\n    bandwidth remaining percent 0\n  class type queuing c-out-8q-q1\n    bandwidth remaining percent 0\n  class type queuing c-out-8q-q-default\n    bandwidth remaining percent 100\ncopp profile strict\nno system mode maintenance\nsnmp-server contact Kirk Byers\nsnmp-server location Freemont, CA (not really)\nsnmp-server user admin network-admin auth md5 0x9915eb9e8b3d04fdddad4cc3f0739a21 priv 0x9915eb9e8b3d04fdddad4cc3f0739a21 localizedkey\nsnmp-server user pyclass network-admin auth md5 0xb4a54cca3ed197cdd5af29aab83b42a7 priv 0xb4a54cca3ed197cdd5af29aab83b42a7 localizedkey\nsnmp-server user admin auth md5 0x9e902c388e9b4c616e7c7c98d1079325 priv 0x9e902c388e9b4c616e7c7c98d1079325 localizedkey engineID 128:0:0:9:3:0:12:41:209:213:60\nsnmp-server user admin auth md5 0x7357a55b9d35915f72b73fd96443c302 priv 0x7357a55b9d35915f72b73fd96443c302 localizedkey engineID 128:0:0:9:3:0:170:204:136:230:0\nrmon event 1 log description FATAL(1) owner PMON@FATAL\nrmon event 2 log description CRITICAL(2) owner PMON@CRITICAL\nrmon event 3 log description ERROR(3) owner PMON@ERROR\nrmon event 4 log description WARNING(4) owner PMON@WARNING\nrmon event 5 log description INFORMATION(5) owner PMON@INFO\nsnmp-server enable traps link cisco-xcvr-mon-status-chg\ncallhome\n  !#destination-profile CiscoTAC-1 message-level 0\n  !#destination-profile CiscoTAC-1 message-size 5000000\n  !#destination-profile full_txt message-level 0\n  !#destination-profile full_txt message-size 2500000\n  !#destination-profile short_txt message-level 0\n  !#destination-profile short_txt message-size 4000\n  !#periodic-inventory notification interval 7\n  !#periodic-inventory notification timeofday 08:00\nntp server 130.126.24.24 use-vrf management\nntp server 152.2.21.1 use-vrf default\n\nvlan 1\nvlan 2\nvlan 3\nvlan 4\nip prefix-list BMGR-DUMMY-PREFIX-LIST seq 5 permit 169.254.10.10/32 \nroute-map BMGR-DUMMY-ROUTE-MAP permit 10\n  match ip address prefix-list BMGR-DUMMY-PREFIX-LIST \nvrf context management\n  ip route 0.0.0.0/0 10.0.2.2\n\nno nxapi http\nnxapi https port 8443\nno nxapi ssl ciphers weak\nnxapi ssl protocols TLSv1.1 TLSv1.2\n\n\ninterface Vlan1\n\ninterface Ethernet1/1\n  !#no switchport\n  mac-address 000c.29d1.0001\n  no shutdown\n\ninterface Ethernet1/2\n  !#no switchport\n  mac-address 000c.29d1.0002\n  no shutdown\n\ninterface Ethernet1/3\n  !#no switchport\n  mac-address 000c.29d1.0003\n  no shutdown\n\ninterface Ethernet1/4\n  !#no switchport\n  mac-address 000c.29d1.0004\n  no shutdown\n\ninterface Ethernet1/5\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/6\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/7\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/8\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/9\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/10\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/11\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/12\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/13\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/14\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/15\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/16\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/17\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/18\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/19\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/20\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/21\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/22\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/23\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/24\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/25\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/26\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/27\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/28\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/29\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/30\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/31\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/32\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/33\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/34\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/35\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/36\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/37\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/38\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/39\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/40\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/41\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/42\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/43\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/44\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/45\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/46\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/47\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/48\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/49\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/50\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/51\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/52\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/53\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/54\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/55\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/56\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/57\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/58\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/59\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/60\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/61\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/62\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/63\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/64\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/65\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/66\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/67\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/68\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/69\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/70\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/71\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/72\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/73\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/74\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/75\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/76\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/77\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/78\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/79\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/80\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/81\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/82\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/83\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/84\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/85\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/86\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/87\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/88\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/89\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/90\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/91\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/92\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/93\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/94\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/95\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/96\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/97\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/98\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/99\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/100\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/101\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/102\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/103\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/104\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/105\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/106\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/107\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/108\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/109\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/110\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/111\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/112\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/113\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/114\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/115\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/116\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/117\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/118\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/119\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/120\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/121\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/122\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/123\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/124\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/125\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/126\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/127\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/128\n  !#shutdown\n  !#no switchport\n\ninterface mgmt0\n  ip address dhcp\n  vrf member management\ncli alias name wr copy run start\nline console\nline vty\nboot nxos bootflash:/nxos.9.2.3.bin \nrouter bgp 22\nxml server timeout 1200\n\nno priority-flow-control override-interface mode off\n\n!#logging logfile messages 5 size 4194304\n!#logging monitor\n!#logging module\n!#logging console\n\n\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 97, in merge_configs
    parse = CiscoConfParse(task.host["backup_config"])
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/ciscoconfparse/ciscoconfparse.py", line 345, in __init__
    raise RuntimeError
RuntimeError

2023-09-23 16:44:01,230 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'merge_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/ciscoconfparse/ciscoconfparse.py", line 270, in __init__
    f = open(config, **self.openargs)
OSError: [Errno 36] File name too long: '\n!Command: Checkpoint cmd vdc 1\n!Time: Sat Sep 23 23:43:58 2023\n\nversion 9.2(3) Bios:version  \nhostname nxos2\nclass-map type network-qos c-nq1\n  description Default class on qos-group 1\n  match qos-group 1\nclass-map type network-qos c-nq2\n  description Default class on qos-group 2\n  match qos-group 2\nclass-map type network-qos c-nq3\n  description Default class on qos-group 3\n  match qos-group 3\nclass-map type network-qos c-8q-nq1\n  description Default class on qos-group 1\n  match qos-group 1\nclass-map type network-qos c-8q-nq2\n  description Default class on qos-group 2\n  match qos-group 2\nclass-map type network-qos c-8q-nq3\n  description Default class on qos-group 3\n  match qos-group 3\nclass-map type network-qos c-8q-nq4\n  description Default class on qos-group 4\n  match qos-group 4\nclass-map type network-qos c-8q-nq5\n  description Default class on qos-group 5\n  match qos-group 5\nclass-map type network-qos c-8q-nq6\n  description Default class on qos-group 6\n  match qos-group 6\nclass-map type network-qos c-8q-nq7\n  description Default class on qos-group 7\n  match qos-group 7\nclass-map type network-qos c-nq-default\n  description Default class on qos-group 0\n  match qos-group 0\nclass-map type network-qos c-8q-nq-default\n  description Default class on qos-group 0\n  match qos-group 0\npolicy-map type network-qos default-nq-policy\n  class type network-qos c-nq3\n    mtu 1500\n  class type network-qos c-nq2\n    mtu 1500\n  class type network-qos c-nq1\n    mtu 1500\n  class type network-qos c-nq-default\n    mtu 1500\npolicy-map type network-qos default-8q-nq-policy\n  class type network-qos c-8q-nq7\n    mtu 1500\n  class type network-qos c-8q-nq6\n    mtu 1500\n  class type network-qos c-8q-nq5\n    mtu 1500\n  class type network-qos c-8q-nq4\n    mtu 1500\n  class type network-qos c-8q-nq3\n    mtu 1500\n  class type network-qos c-8q-nq2\n    mtu 1500\n  class type network-qos c-8q-nq1\n    mtu 1500\n  class type network-qos c-8q-nq-default\n    mtu 1500\nvdc nxos2 id 1\n  limit-resource vlan minimum 16 maximum 4094\n  limit-resource vrf minimum 2 maximum 4096\n  limit-resource port-channel minimum 0 maximum 511\n  limit-resource u4route-mem minimum 128 maximum 128\n  limit-resource u6route-mem minimum 96 maximum 96\n  limit-resource m4route-mem minimum 58 maximum 58\n  limit-resource m6route-mem minimum 8 maximum 8\n\n!#feature ssh\n!#ssh key rsa 1024\nfeature nxapi\nfeature scp-server\ncfs eth distribute\nfeature bgp\nfeature interface-vlan\nfeature hsrp\nfeature vpc\nfeature lldp\n\nrole name priv-15\n  description This is a system defined privilege role.\n  rule 1 permit read-write  \nrole name priv-14\n  description This is a system defined privilege role.\n  rule 1 permit read-write  \nrole name priv-13\n  description This is a system defined privilege role.\nrole name priv-12\n  description This is a system defined privilege role.\nrole name priv-11\n  description This is a system defined privilege role.\nrole name priv-10\n  description This is a system defined privilege role.\nrole name priv-9\n  description This is a system defined privilege role.\nrole name priv-8\n  description This is a system defined privilege role.\nrole name priv-7\n  description This is a system defined privilege role.\nrole name priv-6\n  description This is a system defined privilege role.\nrole name priv-5\n  description This is a system defined privilege role.\nrole name priv-4\n  description This is a system defined privilege role.\nrole name priv-3\n  description This is a system defined privilege role.\nrole name priv-2\n  description This is a system defined privilege role.\nrole name priv-1\n  description This is a system defined privilege role.\nrole name priv-0\n  description This is a system defined privilege role.\n  rule 10 permit command traceroute6 *\n  rule 9 permit command traceroute *\n  rule 8 permit command telnet6 *\n  rule 7 permit command telnet *\n  rule 6 permit command ping6 *\n  rule 5 permit command ping *\n  rule 4 permit command ssh6 *\n  rule 3 permit command ssh *\n  rule 2 permit command enable *\n  rule 1 permit read  \nno password strength-check\nusername admin password 5 $5$/.ErG6en$vIpgmSARIqTv9N7btcIi2Ie9gdJvIAPKtecRH/a14YB  role network-admin\nusername pyclass password 5 $5$/SRuQL7G$xw4WMR3jIUzqHAZs7FWuIbqJMIAjV7UU5w8XawKHl.1  role network-admin\nusername pyclass passphrase  lifetime 99999 warntime 14 gracetime 3\nip domain-lookup\nip domain-name lasthop.io\nip name-server 8.8.8.8 8.8.4.4\nip name-server 10.0.2.3 use-vrf management\nno system default switchport\nno logging event trunk-status enable\nvlan dot1Q tag native\n!# qos statistics\n!# class-map type queuing match-any c-out-q3\n  !# match qos-group 3\n!# class-map type queuing match-any c-out-q2\n  !# match qos-group 2\n!# class-map type queuing match-any c-out-q1\n  !# match qos-group 1\n!# class-map type queuing match-any c-out-q-default\n  !# match qos-group 0\n!# class-map type queuing match-any c-out-8q-q7\n  !# match qos-group 7\n!# class-map type queuing match-any c-out-8q-q6\n  !# match qos-group 6\n!# class-map type queuing match-any c-out-8q-q5\n  !# match qos-group 5\n!# class-map type queuing match-any c-out-8q-q4\n  !# match qos-group 4\n!# class-map type queuing match-any c-out-8q-q3\n  !# match qos-group 3\n!# class-map type queuing match-any c-out-8q-q2\n  !# match qos-group 2\n!# class-map type queuing match-any c-out-8q-q1\n  !# match qos-group 1\n!# class-map type queuing match-any c-out-8q-q-default\n  !# match qos-group 0\n!# class-map type queuing match-any c-in-q7\n  !# match qos-group 7\n!# class-map type queuing match-any c-in-q6\n  !# match qos-group 6\n!# class-map type queuing match-any c-in-q5\n  !# match qos-group 5\n!# class-map type queuing match-any c-in-q4\n  !# match qos-group 4\n!# class-map type queuing match-any c-in-q3\n  !# match qos-group 3\n!# class-map type queuing match-any c-in-q2\n  !# match qos-group 2\n!# class-map type queuing match-any c-in-q1\n  !# match qos-group 1\n!# class-map type queuing match-any c-in-q-default\n  !# match qos-group 0\npolicy-map type queuing default-out-policy\n  class type queuing c-out-q3\n    priority level 1\n  class type queuing c-out-q2\n    bandwidth remaining percent 0\n  class type queuing c-out-q1\n    bandwidth remaining percent 0\n  class type queuing c-out-q-default\n    bandwidth remaining percent 100\npolicy-map type queuing default-8q-out-policy\n  class type queuing c-out-8q-q7\n    priority level 1\n  class type queuing c-out-8q-q6\n    bandwidth remaining percent 0\n  class type queuing c-out-8q-q5\n    bandwidth remaining percent 0\n  class type queuing c-out-8q-q4\n    bandwidth remaining percent 0\n  class type queuing c-out-8q-q3\n    bandwidth remaining percent 0\n  class type queuing c-out-8q-q2\n    bandwidth remaining percent 0\n  class type queuing c-out-8q-q1\n    bandwidth remaining percent 0\n  class type queuing c-out-8q-q-default\n    bandwidth remaining percent 100\ncopp profile strict\nno system mode maintenance\nsnmp-server contact Kirk Byers\nsnmp-server location Freemont, CA (not really)\nsnmp-server user admin network-admin auth md5 0x9915eb9e8b3d04fdddad4cc3f0739a21 priv 0x9915eb9e8b3d04fdddad4cc3f0739a21 localizedkey\nsnmp-server user pyclass network-admin auth md5 0xb4a54cca3ed197cdd5af29aab83b42a7 priv 0xb4a54cca3ed197cdd5af29aab83b42a7 localizedkey\nsnmp-server user admin auth md5 0x9e902c388e9b4c616e7c7c98d1079325 priv 0x9e902c388e9b4c616e7c7c98d1079325 localizedkey engineID 128:0:0:9:3:0:12:41:209:213:60\nsnmp-server user admin auth md5 0x7357a55b9d35915f72b73fd96443c302 priv 0x7357a55b9d35915f72b73fd96443c302 localizedkey engineID 128:0:0:9:3:0:170:204:136:230:0\nrmon event 1 log description FATAL(1) owner PMON@FATAL\nrmon event 2 log description CRITICAL(2) owner PMON@CRITICAL\nrmon event 3 log description ERROR(3) owner PMON@ERROR\nrmon event 4 log description WARNING(4) owner PMON@WARNING\nrmon event 5 log description INFORMATION(5) owner PMON@INFO\nsnmp-server enable traps link cisco-xcvr-mon-status-chg\ncallhome\n  !#destination-profile CiscoTAC-1 message-level 0\n  !#destination-profile CiscoTAC-1 message-size 5000000\n  !#destination-profile full_txt message-level 0\n  !#destination-profile full_txt message-size 2500000\n  !#destination-profile short_txt message-level 0\n  !#destination-profile short_txt message-size 4000\n  !#periodic-inventory notification interval 7\n  !#periodic-inventory notification timeofday 08:00\nntp server 130.126.24.24 use-vrf management\nntp server 152.2.21.1 use-vrf default\n\nvlan 1\nvlan 2\nvlan 3\nvlan 4\nip prefix-list BMGR-DUMMY-PREFIX-LIST seq 5 permit 169.254.10.10/32 \nroute-map BMGR-DUMMY-ROUTE-MAP permit 10\n  match ip address prefix-list BMGR-DUMMY-PREFIX-LIST \nvrf context management\n  ip route 0.0.0.0/0 10.0.2.2\n\nno nxapi http\nnxapi https port 8443\nno nxapi ssl ciphers weak\nnxapi ssl protocols TLSv1.1 TLSv1.2\n\n\ninterface Vlan1\n\ninterface Ethernet1/1\n  !#no switchport\n  mac-address 000c.29d2.0001\n  no shutdown\n\ninterface Ethernet1/2\n  !#no switchport\n  mac-address 000c.29d2.0002\n  no shutdown\n\ninterface Ethernet1/3\n  !#no switchport\n  mac-address 000c.29d2.0003\n  no shutdown\n\ninterface Ethernet1/4\n  !#no switchport\n  mac-address 000c.29d2.0004\n  no shutdown\n\ninterface Ethernet1/5\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/6\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/7\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/8\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/9\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/10\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/11\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/12\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/13\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/14\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/15\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/16\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/17\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/18\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/19\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/20\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/21\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/22\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/23\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/24\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/25\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/26\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/27\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/28\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/29\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/30\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/31\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/32\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/33\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/34\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/35\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/36\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/37\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/38\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/39\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/40\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/41\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/42\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/43\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/44\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/45\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/46\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/47\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/48\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/49\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/50\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/51\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/52\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/53\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/54\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/55\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/56\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/57\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/58\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/59\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/60\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/61\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/62\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/63\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/64\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/65\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/66\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/67\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/68\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/69\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/70\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/71\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/72\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/73\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/74\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/75\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/76\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/77\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/78\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/79\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/80\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/81\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/82\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/83\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/84\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/85\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/86\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/87\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/88\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/89\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/90\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/91\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/92\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/93\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/94\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/95\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/96\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/97\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/98\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/99\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/100\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/101\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/102\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/103\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/104\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/105\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/106\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/107\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/108\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/109\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/110\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/111\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/112\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/113\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/114\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/115\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/116\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/117\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/118\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/119\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/120\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/121\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/122\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/123\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/124\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/125\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/126\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/127\n  !#shutdown\n  !#no switchport\n\ninterface Ethernet1/128\n  !#shutdown\n  !#no switchport\n\ninterface mgmt0\n  ip address dhcp\n  vrf member management\ncli alias name wr copy run start\nline console\nline vty\nboot nxos bootflash:/nxos.9.2.3.bin \nrouter bgp 22\nxml server timeout 1200\n\nno priority-flow-control override-interface mode off\n\n!#logging logfile messages 5 size 4194304\n!#logging monitor\n!#logging module\n!#logging console\n\n\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 97, in merge_configs
    parse = CiscoConfParse(task.host["backup_config"])
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/ciscoconfparse/ciscoconfparse.py", line 345, in __init__
    raise RuntimeError
RuntimeError

2023-09-23 17:18:00,951 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-23 17:18:08,392 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-23 17:18:14,269 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-23 17:18:14,332 -  nornir.core -     INFO -        run() - Running task 'merge_configs' with args {} on 2 hosts
2023-09-25 16:42:10,079 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-25 16:42:22,724 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-25 16:42:28,128 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-25 16:42:28,190 -  nornir.core -     INFO -        run() - Running task 'merge_configs' with args {} on 2 hosts
2023-09-25 17:21:29,878 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-25 17:21:39,236 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-25 17:21:43,280 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-25 17:21:43,348 -  nornir.core -     INFO -        run() - Running task 'merge_configs' with args {} on 2 hosts
2023-09-25 17:21:43,393 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'merge_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 100, in merge_configs
    obj.insert_after(task.host["prefix_list_config"].splitlines())
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/ciscoconfparse/ccp_util.py", line 97, in wrapper
    func(*args, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/ciscoconfparse/ccp_abc.py", line 332, in insert_after
    retval = self.confobj.insert_after(self, insertstr, atomic=False)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/ciscoconfparse/ccp_util.py", line 97, in wrapper
    func(*args, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/ciscoconfparse/ciscoconfparse.py", line 3185, in insert_after
    self._list.insert(ii + 1, obj)
UnboundLocalError: local variable 'obj' referenced before assignment

2023-09-25 17:21:43,395 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'merge_configs' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/bonus_2/bgp-peer.py", line 100, in merge_configs
    obj.insert_after(task.host["prefix_list_config"].splitlines())
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/ciscoconfparse/ccp_util.py", line 97, in wrapper
    func(*args, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/ciscoconfparse/ccp_abc.py", line 332, in insert_after
    retval = self.confobj.insert_after(self, insertstr, atomic=False)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/ciscoconfparse/ccp_util.py", line 97, in wrapper
    func(*args, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/ciscoconfparse/ciscoconfparse.py", line 3185, in insert_after
    self._list.insert(ii + 1, obj)
UnboundLocalError: local variable 'obj' referenced before assignment

2023-09-25 17:22:47,697 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-25 17:22:55,476 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-25 17:23:00,974 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-25 17:23:01,067 -  nornir.core -     INFO -        run() - Running task 'merge_configs' with args {} on 2 hosts
2023-09-26 11:24:46,150 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-26 11:24:56,485 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-26 11:25:01,104 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-26 11:25:01,179 -  nornir.core -     INFO -        run() - Running task 'merge_configs' with args {} on 2 hosts
2023-09-26 11:26:14,118 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-26 11:26:21,991 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-26 11:26:27,705 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-26 11:26:27,771 -  nornir.core -     INFO -        run() - Running task 'merge_configs' with args {} on 2 hosts
2023-09-26 11:38:08,493 -  nornir.core -     INFO -        run() - Running task 'set_config_flags' with args {} on 2 hosts
2023-09-26 11:38:15,798 -  nornir.core -     INFO -        run() - Running task 'get_checkpoint' with args {} on 2 hosts
2023-09-26 11:38:21,938 -  nornir.core -     INFO -        run() - Running task 'render_configs' with args {} on 2 hosts
2023-09-26 11:38:22,002 -  nornir.core -     INFO -        run() - Running task 'merge_configs' with args {} on 2 hosts
